version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      minor-and-patch:
        applies-to: 'version-updates'
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    cooldown:
      default-days: 3
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: 'build'
      include: 'scope'
    labels:
      - 'dependencies'
