version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: '@angular-devkit/build-angular'
        update-types: ['version-update:semver-major']
      - dependency-name: '@angular/cli'
        update-types: ['version-update:semver-major']
      - dependency-name: 'ng-packagr'
        update-types: ['version-update:semver-major']
