import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier/flat';
import storybook from 'eslint-plugin-storybook';

export default defineConfig([
  js.configs.recommended,
  tseslint.configs.recommended,
  ...storybook.configs['flat/recommended'],
  eslintConfigPrettier,
  globalIgnores([
    '**/node_modules',
    '**/dist',
    '**/*.d.ts',
    '**/compile.js',
    '**/conf.js',
    '**/.www',
    '**/*.config.js',
    '**/*.config.ts',
    '**/_beta',
    'build-css.js',
    'packages/core/components',
    'packages/core/loader',
    'packages/core/stencil.config.ts',
    'packages/core/scripts',
    'packages/angular',
    'packages/angular-17',
    'packages/react',
    'packages/tegel-lite',
    'packages/core/www',
    'packages/core/storybook-static',
    'icons',
    'gulpfile.js',
    'commitlint.config.js',
  ]),
  {
    rules: {
      'no-lonely-if': 'off',
      'indent': 'off',
      'spaced-comment': 'warn',
      'camelcase': 'warn',
      'no-var': 'warn',
      'lines-between-class-members': 'warn',
      'no-throw-literal': 'warn',
      'prefer-arrow-callback': 'warn',
      'arrow-body-style': 'warn',
      'prefer-template': 'warn',
      'import/no-extraneous-dependencies': 'off',
      'import/prefer-default-export': 'off',
      'no-underscore-dangle': 'warn',
      'no-return-assign': 'warn',
      'class-methods-use-this': ['warn', { exceptMethods: ['render'] }],
      'array-callback-return': 'warn', // TODO: Check this if needed ["warn", { "checkForEach": false }]
      'consistent-return': 'warn',
      'no-unused-expressions': 'warn',
      'prefer-destructuring': 'warn', // TODO: Turn this on?
      'object-shorthand': 'warn',
      'eqeqeq': 'warn',
      'prefer-const': 'warn',
      'no-empty-pattern': 'warn',
      'vars-on-top': 'warn',
      'no-shadow': 'warn',
      'no-restricted-globals': 'warn',
      'no-useless-assignment': 'warn',
      'no-prototype-builtins': 'warn',
      'no-useless-concat': 'warn',
      'no-unneeded-ternary': 'warn',
      'no-useless-escape': 'warn',
      'no-await-in-loop': 'warn',
      'curly': 'warn',
      'no-unused-vars': ['warn', { varsIgnorePattern: '^h$' }],
      'no-nested-ternary': 'warn',
      'no-restricted-syntax': 'warn', // TODO: check this - disables for-in related error
      'default-case-last': 'warn',
      'no-restricted-exports': 'warn',
      'no-restricted-imports': [
        'error',
        {
          name: '@stencil/core/internal',
          message: 'Use @stencil/core instead.',
        },
      ],
      'radix': 'warn',
      'no-use-before-define': 'off',
      'no-console': 'off',
      'no-undef': 'off',
      'function-paren-newline': 'off',
      'dot-notation': 'off',
      'no-plusplus': 'off',
      'no-param-reassign': ['error', { props: false }],
      '@typescript-eslint/no-unused-vars': ['warn', { varsIgnorePattern: '^h$' }],
    },
  },
]);
