import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';
import { ValueAccessorConfig, angularOutputTarget } from '@stencil/angular-output-target';
import { reactOutputTarget } from '@stencil/react-output-target';

function getTsConfigFile() {
  if (process.env.STORYBOOK_ENV === 'dev') {
    return 'tsconfig.dev.json';
  }
  return 'tsconfig.prod.json';
}

const angularValueAccessorBindings: ValueAccessorConfig[] = [
  {
    elementSelectors: ['tds-checkbox', 'tds-chip[type="checkbox"]'],
    event: 'tdsChange',
    targetAttr: 'checked',
    type: 'boolean',
  },
  {
    elementSelectors: ['tds-toggle'],
    event: 'tdsToggle',
    targetAttr: 'checked',
    type: 'boolean',
  },
  {
    elementSelectors: ['tds-text-field', 'tds-textarea', 'tds-datetime'],
    event: 'tdsInput',
    targetAttr: 'value',
    type: 'text',
  },
  {
    elementSelectors: ['tds-slider'],
    event: 'tdsChange',
    targetAttr: 'value',
    type: 'number',
  },
  /*
   * tds-dropdown does not need to be configured in this array, since it has to use a custom directive that is defined in the angular package
   */
  /* The radio value accessor generated by stencil does not currently behave as expected.
   * tds-radio-button uses a custom value accessor defined in the angular package
   * https://github.com/ionic-team/stencil-ds-output-targets/issues/434
   */
];

export const config: Config = {
  tsconfig: getTsConfigFile(),
  namespace: 'tegel',
  globalStyle: 'src/global/global.scss',
  extras: {
    enableImportInjection: true,
    tagNameTransform: true,
  },
  plugins: [sass()],
  sourceMap: false,
  testing: {
    browserArgs: ['--headless=new'],
  },
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
      copy: [
        {
          src: '../../../typography/fonts',
          dest: 'assets/fonts',
          warn: true,
        },
      ],
    },
    angularOutputTarget({
      componentCorePackage: '@scania/tegel',
      outputType: 'component',
      directivesProxyFile: '../angular/projects/components/src/lib/stencil-generated/components.ts',
      directivesArrayFile: '../angular/projects/components/src/lib/stencil-generated/index.ts',
      valueAccessorConfigs: angularValueAccessorBindings,
    }),
    reactOutputTarget({
      componentCorePackage: '@scania/tegel',
      proxiesFile: '../react/lib/components/stencil-generated/index.ts',
    }),
    angularOutputTarget({
      componentCorePackage: '@scania/tegel',
      outputType: 'component',
      directivesProxyFile:
        '../angular-17/projects/components/src/lib/stencil-generated/components.ts',
      directivesArrayFile: '../angular-17/projects/components/src/lib/stencil-generated/index.ts',
      valueAccessorConfigs: angularValueAccessorBindings,
    }),
    {
      type: 'dist-custom-elements',
      generateTypeDeclarations: true,
      customElementsExportBehavior: 'auto-define-custom-elements',
      externalRuntime: false,
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
  ],
};
