name: Cleanup Old Dry Run Branches

on:
  schedule:
    - cron: '0 4 * * 1-5' # Runs every weekday at 06:00 CET/CEST (04:00 UTC)
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set Git identity
        run: |
          git config --global user.name "Tegel - Scania"
          git config --global user.email "tegel.design.system@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Set Git identity
        run: |
          git config --global user.name "Tegel - Scania" 
          git config --global user.email "tegel.design.system@gmail.com"
          env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        uses: cli/setup-gh@v4
        with:
          version: latest

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Remove old dry-run branches
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Looking for dry-run branches older than 2 days..."

          gh api --paginate repos/${{ github.repository }}/branches \
            | jq -r '.[] | select(.name | test("dry-run-[0-9]{8}-[0-9]{4}")) | .name' \
            | while read branch; do
                echo "🔍 Found branch: $branch"

                timestamp=$(echo "$branch" | grep -oE '[0-9]{8}-[0-9]{4}')
                echo "📆 Extracted timestamp: $timestamp"

                branch_date=$(date -d "${timestamp:0:8} ${timestamp:9:2}:${timestamp:11:2}" +%s || echo 0)
                now=$(date +%s)
                age=$(( (now - branch_date) / 86400 ))

                echo "📆 Branch age: $age days"

                if [ "$branch_date" -eq 0 ]; then
                  echo "⚠️ Failed to parse timestamp for $branch — skipping"
                  continue
                fi

                # Only delete branches that are older than or equal to 2 full days.
                if [ "$age" -ge 2 ]; then
                  echo "🗑 Deleting $branch (via git)..."
                  git push --no-verify origin --delete "$branch" || {
                    echo "⚠️ Git push failed, trying GH API delete..."
                    gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/"$branch" || \
                    echo "❌ Failed to delete $branch via GH API"
                  }
                else
                  echo "✅ Keeping $branch (age: $age)"
                fi
              done
