name: Cleanup Old Dry Run Branches

on:
  schedule:
    - cron: '0 4 * * 1-5' # Runs every weekday at 06:00 CET/CEST (04:00 UTC)
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old dry-run branches
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "🔍 Looking for dry-run branches older than 2 days..."

          gh api repos/${{ github.repository }}/branches \
            | jq -r '.[] | select(.name | test("-dry-run-[0-9]{8}-[0-9]{4}$")) | .name' \
            | while read branch; do
                timestamp=$(echo "$branch" | grep -oE '[0-9]{8}-[0-9]{4}')
                branch_date=$(date -d "${timestamp:0:8} ${timestamp:9:2}:${timestamp:11:2}" +%s || echo 0)
                now=$(date +%s)
                age=$(( (now - branch_date) / 86400 ))
                if [ "$branch_date" -eq 0 ]; then
                  echo "⚠️ Unable to parse timestamp for $branch — skipping"
                  continue
                fi
                if [ "$age" -gt 2 ]; then
                  echo "🗑 Deleting branch $branch (age: $age days)"
                  git push --no-verify origin --delete "$branch"
                else
                  echo "✅ Keeping branch $branch (age: $age days)"
                fi
              done
