name: Merge develop into test
on:
  workflow_dispatch:
jobs:
  merge-develop-into-test:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Set up Git for authentication
        run: |
          git config --global user.name "Tegel - Scania"
          git config --global user.email "tegel.design.system@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Merge develop into test
        run: |
          git checkout holy-main
          git merge --squash -X theirs develop
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: merging develop into holy-main"
            git push --force --no-verify origin holy-main
          else
            echo "No changes to commit in holy-main"
          fi
