name: Playwright
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: packages/core
        run: npm ci

      - name: Build Tegel
        working-directory: packages/core
        run: npm run build

      - name: Run Playwright tests
        working-directory: packages/core
        run: npx playwright test
        env:
          HOME: /root

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: ./packages/core/results.json

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-output
          path: ./packages/core/test-results/output ## Folder used in playwright.config.js `outputDir`
          retention-days: 1
