name: Playwright
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: packages/core
        run: npm ci

      - name: Build Tegel
        working-directory: packages/core
        run: npm run build

      - name: Run Playwright tests in Docker
        working-directory: packages/core
        run: >
          docker run --rm --network host
          -v ${{ github.workspace }}/packages/core:/work/
          -w /work/
          mcr.microsoft.com/playwright:v1.56.1-jammy
          /bin/bash -c "npx playwright test"

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: ./packages/core/results.json

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-output
          path: ./packages/core/test-results/output ## Folder used in playwright.config.js `outputDir`
          retention-days: 1
