name: Manual Release @scania/tegel-angular-17
on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: 'Node version'
        required: true
        default: '20.9.0'
        type: string

      tags:
        description: 'Tag'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - dev

      dryRun:
        description: 'Dry run'
        required: false
        default: false
        type: boolean

jobs:
  release-angular-17:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: packages/angular-17
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up node
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.nodeVersion }}
          registry-url: 'https://registry.npmjs.org'

      - name: Set Tegel user
        run: git config --global user.name "Tegel - Scania" && git config --global user.email "tegel.design.system@gmail.com"

      - name: Angular-17 - Read package.json Version
        id: version
        working-directory: packages/angular-17/projects/components
        run: echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Install dependencies in root
        run: npm install

      - name: Core - Install
        working-directory: packages/core
        run: npm install

      - name: Angular-17 workspace - Install
        working-directory: packages/angular-17
        run: npm install

      - name: Angular-17 wrapper - Install
        working-directory: packages/angular-17/projects/components
        run: npm install

      - name: Angular-17 workspace - Install latest tegel package
        working-directory: packages/angular-17
        run: npm install @scania/tegel@${{ steps.version.outputs.PACKAGE_VERSION }}

      - name: Angular-17 wrapper - Install latest tegel package
        working-directory: packages/angular-17/projects/components
        run: npm install @scania/tegel@${{ steps.version.outputs.PACKAGE_VERSION }}

      - name: Angular-17 - Run build
        run: npm run build-angular-17

      - name: Angular-17 - Publish
        working-directory: packages/angular-17/dist/components
        run: |
          if [ "${{ github.event.inputs.dryRun }}" == "true" ]; then
            npm publish --tag ${{ github.event.inputs.tags }} --dry-run
          else
            npm publish --tag ${{ github.event.inputs.tags }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      version: ${{ steps.version.outputs.PACKAGE_VERSION }}

  on-failure:
    needs: release-angular-17
    runs-on: ubuntu-latest
    if: always() && needs.release-angular-17.result == 'failure'

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Remove git tag on failure
        run: |
          tagname="@scania/tegel@${{ needs.release-angular-17.outputs.version }}"
          if git rev-parse $tagname >/dev/null 2>&1; then
            git push origin --delete $tagname
          fi
