name: Smoke test webhook

on:
  push:
    branches:
      - build/smoketest-webhook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run your build or tests
        run: |
          echo "Running build/test..."
          # Replace this with your actual build/test command
          exit 1 # Simulate failure

      - name: Notify Teams on failure
        if: failure()
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          REPO_NAME: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref }}
          COMMIT_SHA: ${{ github.sha }}
          RUN_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "version": "1.0",
                  "body": [
                    {
                      "type": "TextBlock",
                      "size": "Medium",
                      "weight": "Bolder",
                      "text": "Build Failure Notification"
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {
                          "title": "Repository",
                          "value": "'"${REPO_NAME}"'"
                        },
                        {
                          "title": "Branch",
                          "value": "'"${BRANCH_NAME}"'"
                        },
                        {
                          "title": "Commit",
                          "value": "'"${COMMIT_SHA}"'"
                        }
                      ]
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "View failed jobs",
                      "url": "'"${RUN_URL}"'"
                    }
                  ]
                }
              }
            ]
          }' "$TEAMS_WEBHOOK_URL"
